spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: product-service
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: logs/order-service.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/order-service-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB